### ISSUE TITLE
test ##Extract optical flow of a single video##

### ISSUE THREAD

**Issue by Shuhan136** [open-mmlab/denseflow#10]
x@x:/data1/zsh/mmaction-master/third_party/denseflow/build$ make install
[ 66%] Built target zzdenseflow
[100%] Built target denseflow
Install the project...
-- Install configuration: ""
-- Installing: /home/x/app/bin/denseflow
-- Set runtime path of "/home/x/app/bin/denseflow" to ""
-- Installing: /home/x/app/lib/libzzdenseflow.a
(base) x@x:/data1/zsh/mmaction-master/third_party/denseflow/build$ denseflow test.avi -b=20 -a=tvl1 -s=1 -v
 denseflow: command not found

**Comment by zhuangyuan97** [comment]
Hi, I also encountered this problem. How did you solve it？

**Comment by innerlee** [comment]
Add it to PATH
