### ISSUE TITLE
about save RGB feature and optical flow feature in .h5 

### ISSUE THREAD

**Issue by Shuhan136** [open-mmlab/denseflow#11]
1.   denseflow test.avi -b=20 -a=tvl1 -s=1 --saveType=h5 -v
terminate called after throwing an instance of 'std::runtime_error'
  what():  HDF5 support is not enabled, pls recompile
Aborted (core dumped)
I can't save output in .h5
2.   how can I get the RGB feature (in .h5）

**Comment by innerlee** [comment]
when compiling, enable the HDF5 option. see README for more detail. and dont forget to install hdf5 dependency

```bash
cmake -DCMAKE_INSTALL_PREFIX=$HOME/app -DUSE_HDF5=yes..
```

**Comment by innerlee** [comment]
btw hdf5 is very large. png is also lossless, but i haven't wrote a decoder yet

**Comment by Shuhan136** [comment]
One more question, If I get RGB feature and optical flow feature in .h5 format, is each frame a vector in the .h5 file? 

For example, a video (has 5000 frames) whose RGB feature is [5000, 1024] and optical flow feature is [5000, 1024] in .h5 file?

**Comment by innerlee** [comment]
you can use command line tools `h5ls` to display the structure of the saved h5 file.
actually each frame is saved as a dataset in the file.

**Comment by innerlee** [comment]
btw i guess the file size of 5000 frames might be huge

**Comment by Shuhan136** [comment]
thanks very much!
