### ISSUE TITLE
make -j error

### ISSUE THREAD

**Issue by dingyf0523** [open-mmlab/denseflow#16]
make -j步骤出现如下错误：
(open-mmlab) uk@uk-X299-WU8:~/Workspaces/denseflow/build$ make -j
Scanning dependencies of target zzdenseflow
[ 16%] Building CXX object CMakeFiles/zzdenseflow.dir/src/common.cpp.o
[ 33%] Building CXX object CMakeFiles/zzdenseflow.dir/src/utils.cpp.o
[ 50%] Building CXX object CMakeFiles/zzdenseflow.dir/src/denseflow_gpu.cpp.o
[ 66%] Linking CXX static library libzzdenseflow.a
[ 66%] Built target zzdenseflow
Scanning dependencies of target denseflow
[ 83%] Building CXX object CMakeFiles/denseflow.dir/tools/denseflow.cpp.o
[100%] Linking CXX executable denseflow
libzzdenseflow.a(denseflow_gpu.cpp.o)：在函数‘DenseFlow::calc_optflows_imp(FlowBuffer const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int, bool, cv::cuda::Stream&)’中：
denseflow_gpu.cpp:(.text+0x296b)：对‘cv::cuda::OpticalFlowDual_TVL1::create(double, double, double, int, int, double, int, double, double, bool)’未定义的引用
denseflow_gpu.cpp:(.text+0x2a08)：对‘cv::cuda::FarnebackOpticalFlow::create(int, double, bool, int, int, int, double, int)’未定义的引用
denseflow_gpu.cpp:(.text+0x2a9f)：对‘cv::cuda::BroxOpticalFlow::create(double, double, double, int, int, int)’未定义的引用
/home/uk/anaconda3/lib/libharfbuzz.so.0：对‘FT_Done_MM_Var’未定义的引用
//lib/x86_64-linux-gnu/libblkid.so.1：对‘uuid_unparse@UUID_1.0’未定义的引用
collect2: error: ld returned 1 exit status
CMakeFiles/denseflow.dir/build.make:174: recipe for target 'denseflow' failed
make[2]: *** [denseflow] Error 1
CMakeFiles/Makefile2:123: recipe for target 'CMakeFiles/denseflow.dir/all' failed
make[1]: *** [CMakeFiles/denseflow.dir/all] Error 2
Makefile:148: recipe for target 'all' failed
make: *** [all] Error 2

cmake 步骤正常：
(open-mmlab) uk@uk-X299-WU8:~/Workspaces/denseflow/build$ cmake -DCMAKE_INSTALL_PREFIX=$HOME/app -DUSE_HDF5=no -DUSE_NVFLOW=no ..
-- The C compiler identification is GNU 7.5.0
-- The CXX compiler identification is GNU 7.5.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Performing Test COMPILER_SUPPORTS_CXX11
-- Performing Test COMPILER_SUPPORTS_CXX11 - Success
-- Performing Test COMPILER_SUPPORTS_CXX0X
-- Performing Test COMPILER_SUPPORTS_CXX0X - Success
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found CUDA: /usr/local/cuda-10.0 (found version "10.0") 
-- Found OpenCV: /usr/local (found version "4.4.0") 
-- OpenCV library status:
--     config: /usr/local/lib/cmake/opencv4
--     version: 4.4.0
--     libraries: opencv_calib3d;opencv_core;opencv_dnn;opencv_features2d;opencv_flann;opencv_gapi;opencv_highgui;opencv_imgcodecs;opencv_imgproc;opencv_ml;opencv_objdetect;opencv_photo;opencv_stitching;opencv_video;opencv_videoio
--     include path: /usr/local/include/opencv4
-- Found Boost: /usr/include (found version "1.65.1") found components: date_time filesystem iostreams system regex 
-- Boost library status:
--     version: 106501
--     libraries: /usr/lib/x86_64-linux-gnu/libboost_date_time.so;/usr/lib/x86_64-linux-gnu/libboost_filesystem.so;/usr/lib/x86_64-linux-gnu/libboost_iostreams.so;/usr/lib/x86_64-linux-gnu/libboost_system.so;/usr/lib/x86_64-linux-gnu/libboost_regex.so
--     include path: /usr/include
-- Configuring done
-- Generating done
-- Build files have been written to: /home/uk/Workspaces/denseflow/build

**Comment by innerlee** [comment]
is opencv compiled with cuda support?

**Comment by dingyf0523** [comment]
> is opencv compiled with cuda support?

Thanks! Let me check out it.

**Comment by dingyf0523** [comment]
> is opencv compiled with cuda support?

opencv is compiled with cuda support. 
I followed this file: https://github.com/open-mmlab/denseflow/blob/master/INSTALL.md
