### ISSUE TITLE
encounter issue when installing

### ISSUE THREAD

**Issue by wangzheallen** [open-mmlab/denseflow#3]
https://github.com/open-mmlab/denseflow/blob/master/INSTALL.md
when I ran ./zzdenseflow.sh, I got

CMake Error at CMakeLists.txt:67 (install):
  install TARGETS given no ARCHIVE DESTINATION for static library target
  "zzdenseflow".

when I read CMakeFiles/CMakeError.log, I got

/usr/bin/cc -fPIC     CMakeFiles/cmTC_b7f79.dir/CheckSymbolExists.c.o  -o cmTC_b7f79
CMakeFiles/cmTC_b7f79.dir/CheckSymbolExists.c.o: In function `main':
CheckSymbolExists.c:(.text+0x1b): undefined reference to `pthread_create'
collect2: error: ld returned 1 exit status
CMakeFiles/cmTC_b7f79.dir/build.make:86: recipe for target 'cmTC_b7f79' failed

**Comment by innerlee** [comment]
did you `export BOOST_ROOT=$ZZROOT` before install denseflow?

**Comment by innerlee** [comment]
Another try is to remove all anaconda related things in your PATH and LD_LIBRARY_PATH.

Conda is often a trouble when compiling & installing.

**Comment by wangzheallen** [comment]
Thanks for answering!
Still not working, if I ran ./zzdenseflow.sh, I have error as follows in CMakeFiles/CMakeError.log

Run Build Command:"/usr/bin/make" "cmTC_e7dc3/fast"
/usr/bin/make -f CMakeFiles/cmTC_e7dc3.dir/build.make CMakeFiles/cmTC_e7dc3.dir/build
make[1]: Entering directory '/home/ubuntu/denseflow/build/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_e7dc3.dir/CheckFunctionExists.c.o
/usr/bin/cc   -fPIC -DCHECK_FUNCTION_EXISTS=pthread_create   -o CMakeFiles/cmTC_e7dc3.dir/CheckFunctionExists.c.o   -c /usr/local/lib/python3.6/dist-packages/cmake/data/share/cmake-3.13/Modules/CheckFunctionExists.c
Linking C executable cmTC_e7dc3
/usr/local/lib/python3.6/dist-packages/cmake/data/bin/cmake -E cmake_link_script CMakeFiles/cmTC_e7dc3.dir/link.txt --verbose=1
/usr/bin/cc -fPIC -DCHECK_FUNCTION_EXISTS=pthread_create    CMakeFiles/cmTC_e7dc3.dir/CheckFunctionExists.c.o  -o cmTC_e7dc3 -lpthreads
/usr/bin/ld: cannot find -lpthreads
collect2: error: ld returned 1 exit status
CMakeFiles/cmTC_e7dc3.dir/build.make:86: recipe for target 'cmTC_e7dc3' failed
make[1]: *** [cmTC_e7dc3] Error 1
make[1]: Leaving directory '/home/ubuntu/denseflow/build/CMakeFiles/CMakeTmp'
Makefile:121: recipe for target 'cmTC_e7dc3/fast' failed
make: *** [cmTC_e7dc3/fast] Error 2


-------------------
If I ran 'cmake -DCMAKE_INSTALL_PREFIX=$HOME/app -DUSE_HDF5=no -DUSE_NVFLOW=no ..'
with correction from https://stackoverflow.com/questions/14990343/cmake-error-targets-given-no-library-destination-for-shared-library-target : adding line "ARCHIVE DESTINATION lib"

I can compile but cannot install, if I ran 'make -j', I got  fatal error: opencv2/cudaarithm.hpp: No such file or directory
 #include "opencv2/cudaarithm.hpp".
I already export OPENCV_DIR

**Comment by innerlee** [comment]
is the opencv compiled with cuda?

**Comment by wangzheallen** [comment]
> is the opencv compiled with cuda?

I mv anaconda3 to anaconda3_bk and check the python I am using is /usr/bin/python2.7,
 then recompile everything following https://github.com/open-mmlab/denseflow/blob/master/INSTALL.md

**Comment by innerlee** [comment]
Could you check if OpenCV is compiled with CUDA?

You may run zzopencv again, and look at its summary when it prints.

**Comment by wangzheallen** [comment]
Reran zzopencv and getting following summary (only copy cuda related):


-- CUDA detected: 10.0
-- CUDA NVCC target flags: -gencode;arch=compute_30,code=sm_30;-gencode;arch=compute_35,code=sm_35;-gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_52,code=sm_52;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-D_FORCE_INLINES
-- LAPACK(OpenBLAS): LAPACK_LIBRARIES: /usr/local/lib/libopenblas.so
-- LAPACK(OpenBLAS): Support is enabled.


--   NVIDIA CUDA:                   YES (ver 10.0, CUFFT CUBLAS FAST_MATH)
--     NVIDIA GPU arch:             30 35 37 50 52 60 61 70 75
--     NVIDIA PTX archs:
--
--   cuDNN:                         YES (ver 7.5.1)
--
--   OpenCL:                        YES (no extra features)
--     Include path:                /home/ubuntu/app/src/opencv/3rdparty/include/opencl/1.2
--     Link libraries:              Dynamic load
--
--   Python (for build):            /usr/bin/python
--
--   Install to:                    /home/ubuntu/app

**Comment by innerlee** [comment]
Looks like opencv is okay. Could rm the denseflow dir in $ZZROOT/src/denseflow and rerun the installation? In the meantime, look at its output, and find which opencv it is using.

I guess it finds the wrong opencv (without cuda). Also, did you `export OpenCV_DIR=$ZZROOT` before installing denseflow?

**Comment by wangzheallen** [comment]
Thanks for the kind answer! Below are keys to solve the problems.
1. add ARCHIVE DESTINATION lib, before LIBRARY DESTINATION lib in CMakelist.txt
2. clean everything (anaconda )before start installing. I delete all the app directory and reinstall everything follow https://github.com/open-mmlab/denseflow/blob/master/INSTALL.md
3. I export PATH, INCLUDE_PATH, LD_LIBRARY_PATH, CPLUS_INCLUDE_PATH, before installing Opencv.

**Comment by innerlee** [comment]
Glad you solved it! If the CMakelist.txt or the install scripts could be improved, would you mind make a pr?
