### ISSUE TITLE
Want to resume denseflow but cannot manually find .done folder

### ISSUE THREAD

**Issue by MakeCent** [open-mmlab/denseflow#30]
After an denseflow iteruption, I want to resume my denseflow work for extracting optical-flow for folder videos but skip done videos. I notice that there is a --force argument which can control if skip marked as .done videos. While I cannot find any generated folder or file named as 'done' in output dir or source_dir.

Is it OK to run the same command to resume my work, will it skip done videos? Where can I find .done folder and can I manually edit it?

**Comment by innerlee** [comment]
folders with name starting with dot is by default hidden by file exploreres. you can try to rerun the same command and see if it is smart

**Comment by mytk2012** [comment]
Do you succeed in installing opencv？Can you give me some advice about installation,i totally follow the instructions,but failed.

**Comment by mytk2012** [comment]
Otherwise apply mmacion v1.0,this can work,mmaction v2.0 installation denseflow so bad.
