### ISSUE TITLE
How the optical flow is encoded in PNG?

### ISSUE THREAD

**Issue by DeeperMind** [open-mmlab/denseflow#32]
I noticed that when save type is set to 'png', each optical flow frame is saved in one png image. But:
1. Optical flow frames should be of the demension (H,W,2), but the png files are of the shape (H,W,3). How optical flow are encoded into these png files?
2. in #11, @innerlee says that png is lossless, which I do not understand. Optical flow are floats, and can be negative. How can png save such data without loss?

**Comment by innerlee** [comment]
https://github.com/open-mmlab/denseflow/blob/38807cc0a714ead0c43e998d5adf3d913ec6b93a/README.md

**Comment by innerlee** [comment]
https://github.com/open-mmlab/denseflow/blob/master/src/common.cpp#L18-L46
