### ISSUE TITLE
c++: error: unrecognized command line option ‘-Wimplicit-fallthrough=3’; did you mean ‘-Wno-fallthrough’?

### ISSUE THREAD

**Issue by zhaijianyang** [open-mmlab/denseflow#35]
-- Configuring done
-- Generating done
-- Build files have been written to: /home/zhai/app/src/opencv/build
[  0%] Built target gen-pkgconfig
[  0%] Built target quirc
[  2%] Built target zlib
[  2%] Built target ittnotify
[  5%] Built target libjasper
[  9%] Built target libjpeg-turbo
[  9%] Built target opencv_videoio_plugins
[  9%] Building CXX object modules/cudev/CMakeFiles/opencv_cudev.dir/src/stub.cpp.o
[ 10%] Built target ade
[ 11%] Built target libpng
[ 14%] Built target libtiff
[ 23%] Built target libwebp
c++: error: unrecognized command line option ‘-Wimplicit-fallthrough=3’; did you mean ‘-Wno-fallthrough’?
modules/cudev/CMakeFiles/opencv_cudev.dir/build.make:81: recipe for target 'modules/cudev/CMakeFiles/opencv_cudev.dir/src/stub.cpp.o' failed
make[2]: *** [modules/cudev/CMakeFiles/opencv_cudev.dir/src/stub.cpp.o] Error 1
CMakeFiles/Makefile2:3665: recipe for target 'modules/cudev/CMakeFiles/opencv_cudev.dir/all' failed
make[1]: *** [modules/cudev/CMakeFiles/opencv_cudev.dir/all] Error 2
make[1]: *** 正在等待未完成的任务....
[ 29%] Built target libprotobuf
[ 37%] Built target IlmImf
Makefile:181: recipe for target 'all' failed
make: *** [all] Error 2
opencv installed on /home/zhai/app
add following line to .zshrc
export OpenCV_DIR=/home/zhai/app

**Comment by zhaijianyang** [comment]
how to solve this problem？

**Comment by innerlee** [comment]
What's the gcc version, cmake version, and cuda version? I guess they are not compatible

**Comment by zhaijianyang** [comment]
> What's the gcc version, cmake version, and cuda version? I guess they are not compatible

yes, thanks
