### ISSUE TITLE
nasm/yasm not found or too old. Use --disable-x86asm for a crippled build.

### ISSUE THREAD

**Issue by unyxs281** [open-mmlab/denseflow#36]
当执行./zzffmpeg.sh时，提示nasm/yasm not found or too old. Use --disable-x86asm for a crippled build.，但是nasm和yasm已经安装了，这是什么原因内，也尝试了更新nasm和yasm的版本。还是出现这个错误。

**Comment by innerlee** [comment]
Pls show the output of

```bash
echo $PATH
echo $LD_LIBRARY_PATH
ls $HOME/app/bin
ls $HOME/app/lib
```

**Comment by unisoc281** [comment]
> Pls show the output of
> 
> ```shell
> echo $PATH
> echo $LD_LIBRARY_PATH
> ls $HOME/app/bin
> ls $HOME/app/lib
> which nasm
> which yasm
> ```

![image](https://user-images.githubusercontent.com/74952328/110431849-4b0fe400-80e9-11eb-944c-8c41280591eb.png)

**Comment by innerlee** [comment]
See the usage here https://github.com/innerlee/setup#usage

**Comment by unisoc281** [comment]
> See the usage here https://github.com/innerlee/setup#usage

![image](https://user-images.githubusercontent.com/74952328/110436674-7990bd80-80ef-11eb-842c-23ff0cb05516.png)
我是按照这个步骤安装的。代码没有做改动，这是什么原因呢？谢谢。

**Comment by innerlee** [comment]
You can try this docker https://github.com/open-mmlab/denseflow/blob/master/docker/Dockerfile

**Comment by sxl142** [comment]
> 当执行./zzffmpeg.sh时，提示nasm/yasm not found or too old. Use --disable-x86asm for a crippled build.，但是nasm和yasm已经安装了，这是什么原因内，也尝试了更新nasm和yasm的版本。还是出现这个错误。

source ~/.bashrc 应该就好了

**Comment by kuangxiaoye** [comment]
> 

哇！！！！！！！！感谢 ！！！！解决了！！！！

我一直以为./bashrc是实时编译的···呜呜··· 太感谢了！！

我要去仔细看看这个文件是干啥的···
