### ISSUE TITLE
no kernel image is available for execution on the device in function 'call'

### ISSUE THREAD

**Issue by rlleshi** [open-mmlab/denseflow#39]
Full Error: 

```
terminate called after throwing an instance of 'cv::Exception'
  what():  OpenCV(4.5.2) /opencv_contrib/modules/cudev/include/opencv2/cudev/grid/detail/transform.hpp:312: error: (-217:Gpu API call) no kernel image is available for execution on the device in function 'call'

Aborted (core dumped)
```

This is by using the dockerfile. 
GPUs: 2x Geforce RTX; 3090 2x Geforce RTX 2080 Ti.

I tried to to use the above GPUs separately but didn't help. In general, they both work with `CUDA 11`. Also can't see any reason why `OpenCV` wouldn't work with either of them.

Any ideas? Thanks a lot!

**Comment by innerlee** [comment]
For the docker file, you need to adapt the arguments to your environement. See this line https://github.com/open-mmlab/denseflow/blob/master/docker/Dockerfile#L8

2080ti is TURING, btw

**Comment by priyamdey** [comment]
I am getting this error when trying to run the built docker image:

**Comment by innerlee** [comment]
The dockerfile has set up the entrypoint, so you may search how to use it
