### ISSUE TITLE
target "Eigen3::Eigen"  error

### ISSUE THREAD

**Issue by Tortoise17** [open-mmlab/denseflow#43]
I am facing error while compilation. Tried to fix several ways and unsuccessful. 
Can you hint me which flag needed to add to fix this in CMAKE?

```
CMake Error at CMakeLists.txt:36 (add_library):
  Target "zzdenseflow" links to target "Eigen3::Eigen" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?
```

**Comment by innerlee** [comment]
Do you have anaconda in PATH? If so, please try to remove it when compiling (can add it back after installation)

**Comment by Tortoise17** [comment]
@innerlee I tried now twice. It is the same.

**Comment by Tortoise17** [comment]
I tried in all ways. Extremely fresh install. no conda in shell env. no conda in terminal. using CentOS 7. OpenCV 3.5 / 4.5.0 tried both. and complete failing . ending with the above mentioned error.

**Comment by innerlee** [comment]
Hi @Tortoise17 do you want to try docker? we have a docker file. You can modify the cuda option in the beginning of the file.

Debugging system problems via github is nearly impossible. From the message, it says that cmake cannot find Eigen3.
* case 1: Eigen3 is not installed on the system. Then maybe try `sudo apt install libeigen3-dev` or install from source, or seek for help from google/stackoverflow 
* case 2: Multi-version of Eigen3 was installed, and somehow cmake was confused. Cmake has a reputation of hard to debug. I do not understand cmake either.

**Comment by Tortoise17** [comment]
If you have, please share. I would like to try for sure docker. 
It would be really kind if you can share docker file. Than I can also share my experience.

**Comment by innerlee** [comment]
https://github.com/open-mmlab/denseflow/tree/master/docker

**Comment by Tortoise17** [comment]
For CentOS this also didn't work

**Comment by Tortoise17** [comment]
Thank you great man. It finally worked

**Comment by Tortoise17** [comment]
@innerlee thank you so much.

**Comment by innerlee** [comment]
You are welcome!
