### ISSUE TITLE
CUDA_TOOLKIT_ROOT_DIR

### ISSUE THREAD

**Issue by worthlessFella** [open-mmlab/denseflow#46]
while trying to install denseflow I got the following error

`denseflow will be installed in /home/rick/app
Dependency: boost, opencv
downloads/denseflow.tar.gz exist
CMake Error at /usr/local/share/cmake-3.13/Modules/FindCUDA.cmake:696 (message):
  Specify CUDA_TOOLKIT_ROOT_DIR
Call Stack (most recent call first):
  CMakeLists.txt:18 (find_package)

-- Configuring incomplete, errors occurred!
See also "/home/rick/app/src/denseflow/build/CMakeFiles/CMakeOutput.log".
`

All the previous steps were successfull I have nvidia driver and cuda installed 

`(base) rick@rick-MS-7881:~/setup$ nvidia-smi 
Sat Oct  9 09:07:51 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.84       Driver Version: 460.84       CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  RTX A5000           Off  | 00000000:02:00.0  On |                  Off |
| 30%   34C    P8    13W / 230W |    365MiB / 24253MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A      1392      G   /usr/lib/xorg/Xorg                213MiB |
|    0   N/A  N/A      1621      G   /usr/bin/gnome-shell              113MiB |
|    0   N/A  N/A     11861      G   /usr/lib/firefox/firefox            3MiB |
|    0   N/A  N/A     16948      G   /usr/lib/firefox/firefox            3MiB |
|    0   N/A  N/A     17015      G   /usr/lib/firefox/firefox           27MiB |
+-----------------------------------------------------------------------------+
`
Please advice

**Comment by Rahmyyy** [comment]
Hi I have just faced the same issue. Did you find a solution? That would be greatly appreciated if you had a way of solving this. Thanks

My Error:
(/srv/scratch/zID/conda_env/open-mmlab) [zID@k106 build]$ cmake -DCMAKE_INSTALL_PREFIX=$HOME/app -DUSE_HDF5=no -DUSE_NVFLOW=no ..
-- The C compiler identification is GNU 4.8.5
-- The CXX compiler identification is GNU 4.8.5
-- Check for working C compiler: /usr/lib64/ccache/cc
-- Check for working C compiler: /usr/lib64/ccache/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/lib64/ccache/c++
-- Check for working CXX compiler: /usr/lib64/ccache/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Performing Test COMPILER_SUPPORTS_CXX11
-- Performing Test COMPILER_SUPPORTS_CXX11 - Success
-- Performing Test COMPILER_SUPPORTS_CXX0X
-- Performing Test COMPILER_SUPPORTS_CXX0X - Success
CMake Error at /apps/cmake/3.12.1/share/cmake-3.12/Modules/FindCUDA.cmake:692 (message):
  Specify CUDA_TOOLKIT_ROOT_DIR
Call Stack (most recent call first):
  CMakeLists.txt:18 (find_package)
