### ISSUE TITLE
(./zzffmpeg.sh) libvpx enabled but no supported decoders found

### ISSUE THREAD

**Issue by ChengYuChuan** [open-mmlab/denseflow#56]
hello,

I am trying to set up ffmpeg, but I encounter an issue about `libvpx enabled but no supported decoders found`. basically, I ran throught the instruction of it but, when I ran this:

>./configure
>--prefix="$ROOTDIR"
>--extra-libs=-lpthread
>--extra-libs=-lm
>--enable-gpl
>--enable-libx264
>--enable-libx265
>--enable-libvpx
>--enable-nonfree
>--enable-pic
>--enable-shared

it said something like this:

libvpx enabled but no supported decoders found

If you think configure made a mistake, make sure you are using the latest
version from Git. If the latest version fails, report the problem to the
ffmpeg-user@ffmpeg.org mailing list or IRC #ffmpeg on irc.freenode.net.
Include the log file "ffbuild/config.log" produced by configure as this will help
solve the problem.

and my config.log is this:
[config.log](https://github.com/open-mmlab/denseflow/files/7882689/config.log)

additionally, I ran this:
`ffmpeg -codecs | grep vpx`
and I got this:

>ffmpeg version 4.4.1 Copyright (c) 2000-2021 the FFmpeg developers
>  built with gcc 9.4.0 (GCC)
>  configuration: --prefix=/home/cheng/.conda/envs/VSTransformer0114 -->cc=/home/conda/feedstock_root/build_artifacts/ffmpeg_1636205340875/_build_env/bin/x86_64-conda-linux-gnu-cc --disable->doc --disable-openssl --enable-avresample --enable-demuxer=dash --enable-gnutls --enable-gpl --enable-hardcoded-tables -->enable-libfreetype --enable-libopenh264 --enable-vaapi --enable-libx264 --enable-libx265 --enable-libaom --enable-libsvtav1 -->enable-libxml2 --enable-libvpx --enable-pic --enable-pthreads --enable-shared --disable-static --enable-version3 --enable-zlib -->enable-libmp3lame --pkg-config=/home/conda/feedstock_root/build_artifacts/ffmpeg_1636205340875/_build_env/bin/pkg->config
>  libavutil      56. 70.100 / 56. 70.100
>  libavcodec     58.134.100 / 58.134.100
>  libavformat    58. 76.100 / 58. 76.100
>  libavdevice    58. 13.100 / 58. 13.100
>  libavfilter     7.110.100 /  7.110.100
>  libavresample   4.  0.  0 /  4.  0.  0
>  libswscale      5.  9.100 /  5.  9.100
>  libswresample   3.  9.100 /  3.  9.100
>  libpostproc    55.  9.100 / 55.  9.100
> DEV.L. vp8                  On2 VP8 (decoders: vp8 libvpx ) (encoders: libvpx vp8_vaapi )
> DEV.L. vp9                  Google VP9 (decoders: vp9 libvpx-vp9 ) (encoders: libvpx-vp9 vp9_vaapi )

**Comment by innerlee** [comment]
How about removing the `--enable-libvpx`?

**Comment by ChengYuChuan** [comment]
I got the reason why I got the issues.
thx and happy Chinese new year

**Comment by kuangxiaoye** [comment]
> I got the reason why I got the issues. thx and happy Chinese new year

你好 请问可以说一下如何解决咩？感谢！

**Comment by kuangxiaoye** [comment]
> > I got the reason why I got the issues. thx and happy Chinese new year
> 
> 你好 请问可以说一下如何解决咩？感谢！

芜湖 已经解决了 是因为 我一开始libx264.sh  安装失败了，我没管继续安装了vpx.sh，我通过source ~/.bashrc 命令解决libx264问题后。没有重新安装他。

重装后就成功了

**Comment by laohuijiadezhu** [comment]
@kuangxiaoye 你好，请问“没有重新安装他”的他指的是哪个文件？另外，当我执行`./zzlibvpx.sh
`，输出信息是
```
......
    [DEP] tools/tiny_ssim.c.d
    [DEP] y4minput.c.d
    [CC] y4minput.c.o
    [CC] tools/tiny_ssim.c.o
    [LD] tools/tiny_ssim
make[1]: Nothing to be done for 'all'.
    [INSTALL] /root/app/include/vpx/vp8.h
    [INSTALL] /root/app/include/vpx/vp8cx.h
    [INSTALL] /root/app/include/vpx/vpx_ext_ratectrl.h
    [INSTALL] /root/app/include/vpx/vp8dx.h
    [INSTALL] /root/app/include/vpx/vpx_codec.h
    [INSTALL] /root/app/include/vpx/vpx_frame_buffer.h
    [INSTALL] /root/app/include/vpx/vpx_image.h
    [INSTALL] /root/app/include/vpx/vpx_integer.h
    [INSTALL] /root/app/include/vpx/vpx_decoder.h
    [INSTALL] /root/app/include/vpx/vpx_encoder.h
    [INSTALL] /root/app/lib/libvpx.a
    [LN]      libvpx.so.8.0.0 /root/app/lib/libvpx.so
    [LN]      libvpx.so.8.0.0 /root/app/lib/libvpx.so.8
    [LN]      libvpx.so.8.0.0 /root/app/lib/libvpx.so.8.0
    [INSTALL] /root/app/lib/libvpx.so.8.0.0
    [INSTALL] /root/app/lib/pkgconfig/vpx.pc
make[1]: Nothing to be done for 'install'.
make[1]: Nothing to be done for 'install'.
libvpx installed on /root/app
```
这似乎并没有成功安装libvpx，因为`app/bin`中并没有libvpx相关的文件。您知道这是什么原因导致的吗？
Which file does the "he" in "without reinstalling him" refer to? Also, when I execute `./zzlibvpx.sh`, the output  is
```

````
This doesn't seem to install libvpx successfully, because there are no libvpx related files in `app/bin`. Do you know what could be causing this?
