### ISSUE TITLE
error while using ./zzlibx264.sh  script during installation

### ISSUE THREAD

**Issue by fmthoker** [open-mmlab/denseflow#6]
Saving to: 'libx264.tar.gz'

    [ <=>                                                                                                                                        ] 932,833     5.60MB/s   in 0.2s

2020-07-19 21:31:35 (5.60 MB/s) - 'libx264.tar.gz' saved [932833]

Found no assembler
Minimum version is nasm-2.13
If you really want to compile without asm, configure with --disable-asm.
What should be the course of action here?

**Comment by laohuijiadezhu** [comment]
I met the same problem, how did you solve it?
