### ISSUE TITLE
make -j error after open-cv with CUDA is installed

### ISSUE THREAD

**Issue by caposerenity** [open-mmlab/denseflow#63]
Hi, I'm trying to follow this [guide](https://github.com/open-mmlab/denseflow/blob/master/INSTALL.md) to install denseflow, after sucessfully installing opencv 4.4.0 and boost, I fail with the _make -j_ or _./ssdenseflow.sh_

The error message seems to be related with opencv (fail to refer to opencv in denseflow)
`denseflow will be installed in /root/app
Dependency: boost, opencv
downloads/denseflow.tar.gz exist
-- OpenCV library status:
--     config: /root/app/src/opencv/build/
--     version: 4.4.0
--     libraries: opencv_calib3d;opencv_core;opencv_features2d;opencv_flann;opencv_gapi;opencv_highgui;opencv_imgcodecs;opencv_imgproc;opencv_ml;opencv_objdetect;opencv_photo;opencv_stitching;opencv_video;opencv_videoio;opencv_cudaarithm;opencv_cudabgsegm;opencv_cudafeatures2d;opencv_cudafilters;opencv_cudaimgproc;opencv_cudalegacy;opencv_cudaobjdetect;opencv_cudaoptflow;opencv_cudastereo;opencv_cudawarping;opencv_cudev;opencv_fuzzy;opencv_hfs;opencv_img_hash;opencv_intensity_transform;opencv_line_descriptor;opencv_optflow;opencv_phase_unwrapping;opencv_plot;opencv_quality;opencv_rapid;opencv_shape;opencv_structured_light;opencv_superres;opencv_surface_matching;opencv_videostab;opencv_xfeatures2d;opencv_ximgproc;opencv_xobjdetect;opencv_xphoto
--     include path: /root/app/src/opencv/build;/root/app/src/opencv/include;/root/app/src/opencv_contrib/modules/cudev/include;/root/app/src/opencv/modules/core/include;/root/app/src/opencv_contrib/modules/cudaarithm/include;/root/app/src/opencv/modules/flann/include;/root/app/src/opencv/modules/imgproc/include;/root/app/src/opencv_contrib/modules/intensity_transform/include;/root/app/src/opencv/modules/ml/include;/root/app/src/opencv_contrib/modules/phase_unwrapping/include;/root/app/src/opencv_contrib/modules/plot/include;/root/app/src/opencv_contrib/modules/quality/include;/root/app/src/opencv_contrib/modules/surface_matching/include;/root/app/src/opencv_contrib/modules/cudafilters/include;/root/app/src/opencv_contrib/modules/cudaimgproc/include;/root/app/src/opencv_contrib/modules/cudawarping/include;/root/app/src/opencv/modules/features2d/include;/root/app/src/opencv_contrib/modules/fuzzy/include;/root/app/src/opencv_contrib/modules/hfs/include;/root/app/src/opencv_contrib/modules/img_hash/include;/root/app/src/opencv/modules/imgcodecs/include;/root/app/src/opencv_contrib/modules/line_descriptor/include;/root/app/src/opencv/modules/photo/include;/root/app/src/opencv/modules/videoio/include;/root/app/src/opencv_contrib/modules/xphoto/include;/root/app/src/opencv/modules/calib3d/include;/root/app/src/opencv_contrib/modules/cudafeatures2d/include;/root/app/src/opencv_contrib/modules/cudastereo/include;/root/app/src/opencv/modules/highgui/include;/root/app/src/opencv/modules/objdetect/include;/root/app/src/opencv_contrib/modules/rapid/include;/root/app/src/opencv_contrib/modules/shape/include;/root/app/src/opencv_contrib/modules/structured_light/include;/root/app/src/opencv/modules/video/include;/root/app/src/opencv_contrib/modules/xfeatures2d/include;/root/app/src/opencv_contrib/modules/ximgproc/include;/root/app/src/opencv_contrib/modules/xobjdetect/include;/root/app/src/opencv_contrib/modules/cudabgsegm/include;/root/app/src/opencv_contrib/modules/cudalegacy/include;/root/app/src/opencv_contrib/modules/cudaobjdetect/include;/root/app/src/opencv/modules/gapi/include;/root/app/src/opencv_contrib/modules/optflow/include;/root/app/src/opencv/modules/stitching/include;/root/app/src/opencv_contrib/modules/cudaoptflow/include;/root/app/src/opencv_contrib/modules/superres/include;/root/app/src/opencv_contrib/modules/videostab/include
-- Boost library status:
--     version: 1.76.0
--     libraries: Boost::date_time;Boost::filesystem;Boost::iostreams
--     include path: /root/app/include
-- Configuring done
-- Generating done
-- Build files have been written to: /root/app/src/denseflow/build
Consolidate compiler generated dependencies of target zzdenseflow
[ 66%] Built target zzdenseflow
Consolidate compiler generated dependencies of target denseflow
[ 83%] Linking CXX executable denseflow
CMakeFiles/denseflow.dir/tools/denseflow.cpp.o: In function `main':
denseflow.cpp:(.text+0xeb): undefined reference to `cv::CommandLineParser::CommandLineParser(int, char const* const*, std::string const&)'
denseflow.cpp:(.text+0x14e): undefined reference to `cv::CommandLineParser::about(std::string const&)'
denseflow.cpp:(.text+0x24d): undefined reference to `cv::CommandLineParser::has(std::string const&) const'
denseflow.cpp:(.text+0x714): undefined reference to `cv::CommandLineParser::has(std::string const&) const'
denseflow.cpp:(.text+0x77a): undefined reference to `cv::CommandLineParser::has(std::string const&) const'
denseflow.cpp:(.text+0x7e0): undefined reference to `cv::CommandLineParser::has(std::string const&) const'
denseflow.cpp:(.text+0x8b2): undefined reference to `cv::CommandLineParser::has(std::string const&) const'
CMakeFiles/denseflow.dir/tools/denseflow.cpp.o: In function `std::string cv::CommandLineParser::get<std::string>(std::string const&, bool) const':
denseflow.cpp:(.text._ZNK2cv17CommandLineParser3getISsEET_RKSsb[_ZNK2cv17CommandLineParser3getISsEET_RKSsb]+0x42): undefined reference to `cv::CommandLineParser::getByName(std::string const&, bool, cv::Param, void*) const'
CMakeFiles/denseflow.dir/tools/denseflow.cpp.o: In function `int cv::CommandLineParser::get<int>(std::string const&, bool) const':
denseflow.cpp:(.text._ZNK2cv17CommandLineParser3getIiEET_RKSsb[_ZNK2cv17CommandLineParser3getIiEET_RKSsb]+0x38): undefined reference to `cv::CommandLineParser::getByName(std::string const&, bool, cv::Param, void*) const'
libzzdenseflow.a(denseflow_gpu.cpp.o): In function `DenseFlow::get_new_size(cv::VideoCapture const&, std::vector<boost::filesystem::path, std::allocator<boost::filesystem::path> > const&, bool, cv::Size_<int>&, int&)':
denseflow_gpu.cpp:(.text+0x59e): undefined reference to `cv::imread(std::string const&, int)'
libzzdenseflow.a(denseflow_gpu.cpp.o): In function `DenseFlow::extract_frames_video(cv::VideoCapture&, std::vector<boost::filesystem::path, std::allocator<boost::filesystem::path> >&, bool, bool, cv::Size_<int> const&, boost::filesystem::path, bool)':
denseflow_gpu.cpp:(.text+0xa40): undefined reference to `cv::imencode(std::string const&, cv::_InputArray const&, std::vector<unsigned char, std::allocator<unsigned char> >&, std::vector<int, std::allocator<int> > const&)'
libzzdenseflow.a(denseflow_gpu.cpp.o): In function `DenseFlow::extract_frames_only(bool, bool)':
denseflow_gpu.cpp:(.text+0x1033): undefined reference to `cv::VideoCapture::open(std::string const&, int)'
libzzdenseflow.a(denseflow_gpu.cpp.o): In function `DenseFlow::load_frames_batch(cv::VideoCapture&, std::vector<boost::filesystem::path, std::allocator<boost::filesystem::path> > const&, bool, std::vector<cv::Mat, std::allocator<cv::Mat> >&, bool, cv::Size_<int> const&, bool)':
denseflow_gpu.cpp:(.text+0x14fb): undefined reference to `cv::imread(std::string const&, int)'
libzzdenseflow.a(denseflow_gpu.cpp.o): In function `DenseFlow::load_frames(bool, std::string, bool)':
denseflow_gpu.cpp:(.text+0x221e): undefined reference to `cv::VideoCapture::open(std::string const&, int)'
libzzdenseflow.a(common.cpp.o): In function `encodeFlowMap(cv::Mat const&, cv::Mat const&, std::vector<unsigned char, std::allocator<unsigned char> >&, std::vector<unsigned char, std::allocator<unsigned char> >&, int, bool)':
common.cpp:(.text+0xcf6): undefined reference to `cv::imencode(std::string const&, cv::_InputArray const&, std::vector<unsigned char, std::allocator<unsigned char> >&, std::vector<int, std::allocator<int> > const&)'
common.cpp:(.text+0xd8c): undefined reference to `cv::imencode(std::string const&, cv::_InputArray const&, std::vector<unsigned char, std::allocator<unsigned char> >&, std::vector<int, std::allocator<int> > const&)'
libzzdenseflow.a(common.cpp.o): In function `encodeFlowMapPng(cv::Mat const&, cv::Mat const&, std::vector<unsigned char, std::allocator<unsigned char> >&)':
common.cpp:(.text+0x103e): undefined reference to `cv::imencode(std::string const&, cv::_InputArray const&, std::vector<unsigned char, std::allocator<unsigned char> >&, std::vector<int, std::allocator<int> > const&)'
/root/app/lib/libboost_iostreams.so.1.76.0: undefined reference to `std::ios_base::failure[abi:cxx11]::what() const@GLIBCXX_3.4.21'
/root/app/lib/libboost_iostreams.so.1.76.0: undefined reference to `std::iostream_category()@GLIBCXX_3.4.21'
/root/app/src/opencv/build/lib/libopencv_gapi.so.4.4.0: undefined reference to `VTT for std::__cxx11::basic_stringstream<char, std::char_traits<char>, std::allocator<char> >@GLIBCXX_3.4.21'
/root/app/src/opencv/build/lib/libopencv_gapi.so.4.4.0: undefined reference to `std::__throw_out_of_range_fmt(char const*, ...)@GLIBCXX_3.4.20'
/root/app/src/opencv/build/lib/libopencv_core.so.4.4.0: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::find_first_not_of(char const*, unsigned long, unsigned long) const@GLIBCXX_3.4.21'
/root/app/lib/libboost_iostreams.so.1.76.0: undefined reference to `std::ios_base::failure[abi:cxx11]::~cxx11()@GLIBCXX_3.4.21'
/root/app/src/opencv/build/lib/libopencv_video.so.4.4.0: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::assign(char const*)@GLIBCXX_3.4.21'
/root/app/src/opencv/build/lib/libopencv_gapi.so.4.4.0: undefined reference to `std::logic_error::logic_error(char const*)@GLIBCXX_3.4.21'
/root/app/lib/libboost_iostreams.so.1.76.0: undefined reference to `std::__cxx11::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> >::_M_assign(std::__cxx11::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> > const&)@GLIBCXX_3.4.21'
/root/app/src/opencv/build/lib/libopencv_surface_matching.so.4.4.0: undefined reference to `std::__cxx11::basic_ostringstream<char, std::char_traits<char>, std::allocator<char> >::basic_ostringstream(std::_Ios_Openmode)@GLIBCXX_3.4.21'
/root/app/lib/libboost_iostreams.so.1.76.0: undefined reference to `std::ios_base::failure[abi:cxx11]::cxx11(char const*, std::error_code const&)@GLIBCXX_3.4.21'
/root/app/src/opencv/build/lib/libopencv_core.so.4.4.0: undefined reference to `std::__cxx11::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> >::_M_create(unsigned long&, unsigned long)@GLIBCXX_3.4.21'
/root/app/src/opencv/build/lib/libopencv_cudafeatures2d.so.4.4.0: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string()@GLIBCXX_3.4.21'
/root/app/lib/libboost_filesystem.so.1.76.0: undefined reference to `typeinfo for std::_V2::error_category@GLIBCXX_3.4.21'
/root/app/src/opencv/build/lib/libopencv_gapi.so.4.4.0: undefined reference to `__cxa_init_primary_exception@CXXABI_1.3.11'
/root/app/lib/libboost_filesystem.so.1.76.0: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_erase(unsigned long, unsigned long)@GLIBCXX_3.4.21'
/root/app/src/opencv/build/lib/libopencv_gapi.so.4.4.0: undefined reference to `std::__cxx11::basic_stringstream<char, std::char_traits<char>, std::allocator<char> >::basic_stringstream(std::_Ios_Openmode)@GLIBCXX_3.4.21'
/root/app/src/opencv/build/lib/libopencv_gapi.so.4.4.0: undefined reference to `typeinfo for std::thread::_State@GLIBCXX_3.4.22'
/root/app/src/opencv/build/lib/libopencv_core.so.4.4.0: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::find_last_not_of(char const*, unsigned long, unsigned long) const@GLIBCXX_3.4.21'
/root/app/src/opencv/build/lib/libopencv_core.so.4.4.0: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_replace_aux(unsigned long, unsigned long, unsigned long, char)@GLIBCXX_3.4.21'
/root/app/src/opencv/build/lib/libopencv_gapi.so.4.4.0: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_assign(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)@GLIBCXX_3.4.21'
/root/app/src/opencv/build/lib/libopencv_gapi.so.4.4.0: undefined reference to `std::thread::_M_start_thread(std::unique_ptr<std::thread::_State, std::default_delete<std::thread::_State> >, void (*)())@GLIBCXX_3.4.22'
/root/app/src/opencv/build/lib/libopencv_gapi.so.4.4.0: undefined reference to `std::__atomic_futex_unsigned_base::_M_futex_notify_all(unsigned int*)@GLIBCXX_3.4.21'
/root/app/src/opencv/build/lib/libopencv_gapi.so.4.4.0: undefined reference to `std::thread::_State::~_State()@GLIBCXX_3.4.22'
/root/app/lib/libboost_iostreams.so.1.76.0: undefined reference to `typeinfo for std::ios_base::failure[abi:cxx11]@GLIBCXX_3.4.21'
/root/app/src/opencv/build/lib/libopencv_gapi.so.4.4.0: undefined reference to `std::runtime_error::runtime_error(std::runtime_error const&)@GLIBCXX_3.4.21'
/root/app/src/opencv/build/lib/libopencv_core.so.4.4.0: undefined reference to `std::basic_istream<char, std::char_traits<char> >& std::operator>><char, std::char_traits<char>, std::allocator<char> >(std::basic_istream<char, std::char_traits<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&)@GLIBCXX_3.4.21'
/root/app/lib/libboost_filesystem.so.1.76.0: undefined reference to `std::runtime_error::runtime_error(std::runtime_error const&)@GLIBCXX_3.4.21'
/root/app/src/opencv/build/lib/libopencv_gapi.so.4.4.0: undefined reference to `std::__cxx11::basic_stringstream<char, std::char_traits<char>, std::allocator<char> >::~basic_stringstream()@GLIBCXX_3.4.21'
/root/app/src/opencv/build/lib/libopencv_gapi.so.4.4.0: undefined reference to `std::logic_error::logic_error(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)@GLIBCXX_3.4.21'
/root/app/src/opencv/build/lib/libopencv_gapi.so.4.4.0: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::compare(char const*) const@GLIBCXX_3.4.21'
/root/app/src/opencv/build/lib/libopencv_gapi.so.4.4.0: undefined reference to `std::runtime_error::runtime_error(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)@GLIBCXX_3.4.21'
/root/app/lib/libboost_filesystem.so.1.76.0: undefined reference to `std::_V2::error_category::~error_category()@GLIBCXX_3.4.21'
/root/app/src/opencv/build/lib/libopencv_gapi.so.4.4.0: undefined reference to `std::logic_error::logic_error(std::logic_error const&)@GLIBCXX_3.4.21'
/root/app/lib/libboost_filesystem.so.1.76.0: undefined reference to `std::runtime_error::operator=(std::runtime_error const&)@GLIBCXX_3.4.21'
/root/app/lib/libboost_iostreams.so.1.76.0: undefined reference to `std::ios_base::failure[abi:cxx11]::cxx11(char const*, std::error_code const&)@GLIBCXX_3.4.21'
/root/app/lib/libboost_filesystem.so.1.76.0: undefined reference to `std::_V2::error_category::_M_message[abi:cxx11](int) const@GLIBCXX_3.4.21'
/root/app/src/opencv/build/lib/libopencv_surface_matching.so.4.4.0: undefined reference to `vtable for std::__cxx11::basic_ostringstream<char, std::char_traits<char>, std::allocator<char> >@GLIBCXX_3.4.21'
/root/app/src/opencv/build/lib/libopencv_gapi.so.4.4.0: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_append(char const*, unsigned long)@GLIBCXX_3.4.21'
/root/app/lib/libboost_iostreams.so.1.76.0: undefined reference to `std::ios_base::failure[abi:cxx11]::cxx11(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)@GLIBCXX_3.4.21'
/root/app/lib/libboost_filesystem.so.1.76.0: undefined reference to `std::_V2::generic_category()@GLIBCXX_3.4.21'
/root/app/src/opencv/build/lib/libopencv_cudafeatures2d.so.4.4.0: undefined reference to `std::runtime_error::runtime_error(char const*)@GLIBCXX_3.4.21'
/root/app/src/opencv/build/lib/libopencv_videoio.so.4.4.0: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::rfind(char, unsigned long) const@GLIBCXX_3.4.21'
/root/app/src/opencv/build/lib/libopencv_imgcodecs.so.4.4.0: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_construct(unsigned long, char)@GLIBCXX_3.4.21'
/root/app/src/opencv/build/lib/libopencv_core.so.4.4.0: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned long, unsigned long)@GLIBCXX_3.4.21'
/root/app/src/opencv/build/lib/libopencv_cudastereo.so.4.4.0: undefined reference to `__cxa_throw_bad_array_new_length@CXXABI_1.3.8'
/root/app/src/opencv/build/lib/libopencv_gapi.so.4.4.0: undefined reference to `std::logic_error::logic_error(std::logic_error const&)@GLIBCXX_3.4.21'
/root/app/lib/libboost_filesystem.so.1.76.0: undefined reference to `std::__cxx11::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> >::_M_replace(unsigned long, unsigned long, wchar_t const*, unsigned long)@GLIBCXX_3.4.21'
/root/app/src/opencv/build/lib/libopencv_gapi.so.4.4.0: undefined reference to `std::__exception_ptr::exception_ptr::exception_ptr(void*)@CXXABI_1.3.11'
/root/app/src/opencv/build/lib/libopencv_core.so.4.4.0: undefined reference to `VTT for std::__cxx11::basic_istringstream<char, std::char_traits<char>, std::allocator<char> >@GLIBCXX_3.4.21'
/root/app/src/opencv/build/lib/libopencv_gapi.so.4.4.0: undefined reference to `std::runtime_error::runtime_error(char const*)@GLIBCXX_3.4.21'
/root/app/src/opencv/build/lib/libopencv_gapi.so.4.4.0: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::reserve(unsigned long)@GLIBCXX_3.4.21'
/root/app/lib/libboost_filesystem.so.1.76.0: undefined reference to `std::runtime_error::runtime_error(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)@GLIBCXX_3.4.21'
/root/app/src/opencv/build/lib/libopencv_gapi.so.4.4.0: undefined reference to `vtable for std::__cxx11::basic_stringstream<char, std::char_traits<char>, std::allocator<char> >@GLIBCXX_3.4.21'
/root/app/src/opencv/build/lib/libopencv_gapi.so.4.4.0: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::resize(unsigned long, char)@GLIBCXX_3.4.21'
/root/app/src/opencv/build/lib/libopencv_core.so.4.4.0: undefined reference to `std::__cxx11::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> >::find_last_of(wchar_t const*, unsigned long, unsigned long) const@GLIBCXX_3.4.21'
/root/app/src/opencv/build/lib/libopencv_surface_matching.so.4.4.0: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::find(char, unsigned long) const@GLIBCXX_3.4.21'
/root/app/src/opencv/build/lib/libopencv_core.so.4.4.0: undefined reference to `std::__cxx11::basic_istringstream<char, std::char_traits<char>, std::allocator<char> >::~basic_istringstream()@GLIBCXX_3.4.21'
/root/app/src/opencv/build/lib/libopencv_stitching.so.4.4.0: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::find_last_of(char const*, unsigned long, unsigned long) const@GLIBCXX_3.4.21'
/root/app/src/opencv/build/lib/libopencv_objdetect.so.4.4.0: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_mutate(unsigned long, unsigned long, char const*, unsigned long)@GLIBCXX_3.4.21'
/root/app/src/opencv/build/lib/libopencv_surface_matching.so.4.4.0: undefined reference to `VTT for std::__cxx11::basic_ostringstream<char, std::char_traits<char>, std::allocator<char> >@GLIBCXX_3.4.21'
/root/app/src/opencv/build/lib/libopencv_stitching.so.4.4.0: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::operator=(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&&)@GLIBCXX_3.4.21'
/root/app/lib/libboost_iostreams.so.1.76.0: undefined reference to `std::ios_base::failure[abi:cxx11]::~cxx11()@GLIBCXX_3.4.21'
/root/app/src/opencv/build/lib/libopencv_gapi.so.4.4.0: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_replace(unsigned long, unsigned long, char const*, unsigned long)@GLIBCXX_3.4.21'
/root/app/src/opencv/build/lib/libopencv_surface_matching.so.4.4.0: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::compare(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const@GLIBCXX_3.4.21'
/root/app/src/opencv/build/lib/libopencv_core.so.4.4.0: undefined reference to `vtable for std::__cxx11::basic_istringstream<char, std::char_traits<char>, std::allocator<char> >@GLIBCXX_3.4.21'
/root/app/src/opencv/build/lib/libopencv_gapi.so.4.4.0: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_create(unsigned long&, unsigned long)@GLIBCXX_3.4.21'
/root/app/src/opencv/build/lib/libopencv_surface_matching.so.4.4.0: undefined reference to `std::__cxx11::basic_stringbuf<char, std::char_traits<char>, std::allocator<char> >::_M_sync(char*, unsigned long, unsigned long)@GLIBCXX_3.4.21'
/root/app/src/opencv/build/lib/libopencv_core.so.4.4.0: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::find_first_of(char const*, unsigned long, unsigned long) const@GLIBCXX_3.4.21'
/root/app/src/opencv/build/lib/libopencv_surface_matching.so.4.4.0: undefined reference to `std::__cxx11::basic_ostringstream<char, std::char_traits<char>, std::allocator<char> >::~basic_ostringstream()@GLIBCXX_3.4.21'
/root/app/lib/libboost_iostreams.so.1.76.0: undefined reference to `vtable for std::ios_base::failure[abi:cxx11]@GLIBCXX_3.4.21'
/root/app/src/opencv/build/lib/libopencv_imgcodecs.so.4.4.0: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::find(char const*, unsigned long, unsigned long) const@GLIBCXX_3.4.21'
/root/app/src/opencv/build/lib/libopencv_gapi.so.4.4.0: undefined reference to `std::logic_error::logic_error(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)@GLIBCXX_3.4.21'
/root/app/src/opencv/build/lib/libopencv_cudafeatures2d.so.4.4.0: undefined reference to `operator delete(void*, unsigned long)@CXXABI_1.3.9'
/root/app/src/opencv/build/lib/libopencv_surface_matching.so.4.4.0: undefined reference to `std::basic_istream<char, std::char_traits<char> >& std::getline<char, std::char_traits<char>, std::allocator<char> >(std::basic_istream<char, std::char_traits<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, char)@GLIBCXX_3.4.21'
/root/app/src/opencv/build/lib/libopencv_core.so.4.4.0: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::swap(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&)@GLIBCXX_3.4.21'
/root/app/src/opencv/build/lib/libopencv_gapi.so.4.4.0: undefined reference to `vtable for std::__cxx11::basic_stringbuf<char, std::char_traits<char>, std::allocator<char> >@GLIBCXX_3.4.21'
/root/app/src/opencv/build/lib/libopencv_gapi.so.4.4.0: undefined reference to `std::__cxx11::basic_stringbuf<char, std::char_traits<char>, std::allocator<char> >::str() const@GLIBCXX_3.4.21'
collect2: error: ld returned 1 exit status
make[2]: *** [denseflow] Error 1
make[1]: *** [CMakeFiles/denseflow.dir/all] Error 2
make: *** [all] Error 2
denseflow installed on /root/app
`
moreover, the install message of opencv can be found here
[log_opencv.txt](https://github.com/open-mmlab/denseflow/files/8499456/log_opencv.txt)

**Comment by zhengfa1024** [comment]
Hi, how do you solve this problem? I have same problem.

**Comment by caposerenity** [comment]
> Hi, how do you solve this problem? I have same problem.

Hi @zhengfa1024, I solve this by deletcing the opencv dependency installed in /root/app/src, and re-install all the dependency strictly following the sequence listed in https://github.com/open-mmlab/denseflow/blob/master/INSTALL.md
