### ISSUE TITLE
opencv/modules/core/src/parallel.cpp:103:14: fatal error: tbb/tbb_stddef.h: No such file or directory

### ISSUE THREAD

**Issue by dmmSJTU** [open-mmlab/denseflow#68]
hello，when i run ./zzopencv.sh, it report errors: 
/home/daimiaomiao/app/src/opencv/modules/core/src/parallel.cpp:103:14: fatal error: tbb/tbb_stddef.h: No such file or directory
     #include "tbb/tbb_stddef.h"
              ^~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [modules/core/CMakeFiles/opencv_core.dir/build.make:908: modules/core/CMakeFiles/opencv_core.dir/src/parallel.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
[ 34%] Linking CXX static library ../../../../../../lib/libmultiview.a
[ 34%] Built target multiview
[ 34%] Building CXX object modules/sfm/src/libmv/libmv/correspondence/CMakeFiles/correspondence.dir/nRobustViewMatching.cc.o
[ 34%] Building CXX object modules/sfm/src/libmv/libmv/correspondence/CMakeFiles/correspondence.dir/matches.cc.o
[ 34%] Building CXX object modules/sfm/src/libmv/libmv/correspondence/CMakeFiles/correspondence.dir/feature_matching.cc.o
[ 34%] Linking CXX static library ../../../../../../lib/libcorrespondence.a
[ 34%] Built target correspondence
make[1]: *** [CMakeFiles/Makefile2:3146: modules/core/CMakeFiles/opencv_core.dir/all] Error 2
make: *** [Makefile:166: all] Error 2
opencv installed on /home/daimiaomiao/app
add following line to .zshrc
export OpenCV_DIR=/home/daimiaomiao/app
 
Could you give me some solutions about them? Looking forward to your reply.

**Comment by yuf0731** [comment]
Hey,  have you fixed the this problem, I encountered the same one and can you help me to fix it :>

**Comment by yuf0731** [comment]
Hey, have you fixed this problem, I encountered the same one and can you help me to fix it :>
