### ISSUE TITLE
CMAKE ERROR

### ISSUE THREAD

**Issue by arnobanu** [open-mmlab/denseflow#76]
denseflow will be installed in /homearnob/app
Dependency: boost, opencv
downloads/denseflow.tar.gz exist
CMake Error at CMakeLists.txt:19 (find_package):
  By not providing "FindOpenCV.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "OpenCV", but
  CMake did not find one.

  Could not find a package configuration file provided by "OpenCV" with any
  of the following names:

    OpenCVConfig.cmake
    opencv-config.cmake

  Add the installation prefix of "OpenCV" to CMAKE_PREFIX_PATH or set
  "OpenCV_DIR" to a directory containing one of the above files.  If "OpenCV"
  provides a separate development package or SDK, be sure it has been
  installed.

-- Configuring incomplete, errors occurred!
See also "/home/arnob/app/src/denseflow/build/CMakeFiles/CMakeOutput.log".
See also "/home/arnob/app/src/denseflow/build/CMakeFiles/CMakeError.log".

**Comment by arnobanu** [comment]
output of ls app/src

boost      ffmpeg  libx264  nasm    opencv_contrib
denseflow  libvpx  libx265  opencv  yasm

**Comment by louvoinov1** [comment]
@arnobanu Do you mind sharing how you solved this issue? I am getting the same error and can't seem to find a solution..
