### ISSUE TITLE
make denseflow error.

### ISSUE THREAD

**Issue by Shuhan136** [open-mmlab/denseflow#9]
libdenseflow.a(dense_flow_gpu.cpp.o): In function `calcDenseFlowPureGPU(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, int, int, int, int, std::vector<std::vector<unsigned char, std::allocator<unsigned char> >, std::allocator<std::vector<unsigned char, std::allocator<unsigned char> > > >&, std::vector<std::vector<unsigned char, std::allocator<unsigned char> >, std::allocator<std::vector<unsigned char, std::allocator<unsigned char> > > >&, std::vector<std::vector<unsigned char, std::allocator<unsigned char> >, std::allocator<std::vector<unsigned char, std::allocator<unsigned char> > > >&)':
dense_flow_gpu.cpp:(.text+0x1b61): undefined reference to `cv::cudacodec::createVideoReader(cv::String const&)'
collect2: error: ld returned 1 exit status
CMakeFiles/extract_gpu.dir/build.make:154: recipe for target 'extract_gpu' failed
make[2]: *** [extract_gpu] Error 1
CMakeFiles/Makefile2:141: recipe for target 'CMakeFiles/extract_gpu.dir/all' failed
make[1]: *** [CMakeFiles/extract_gpu.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 90%] Built target extract_warp_gpu
[100%] Linking CXX shared library libpydenseflow.so
[100%] Built target pydenseflow
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by innerlee** [comment]
Hi, it seems you are not building this repo. There are no target named `extract_warp_gpu`

**Comment by Shuhan136** [comment]
Thanks for your reply. Can you be more specific, or how to build this repo? I know less about it.

**Comment by Shuhan136** [comment]
> Hi, it seems you are not building this repo. There are no target named `extract_warp_gpu`

Thanks for your reply. Could you be more specific, or how to build this repo. I know less about it.

**Comment by innerlee** [comment]
could you show the result of running `git remote -v`, and `git branch --show-current` and `git rev-parse HEAD`?

**Comment by Shuhan136** [comment]
> could you show the result of running `git remote -v`, and `git branch --show-current` and `git rev-parse HEAD`?

result of running git remote -v :
git remote -vorigin	http://github.com/yjxiong/dense_flow (fetch)
origin	http://github.com/yjxiong/dense_flow (push)

the result of running  git branch --show-current：
error: unknown option `show-current'
usage: git branch [<options>] [-r | -a] [--merged | --no-merged]
   or: git branch [<options>] [-l] [-f] <branch-name> [<start-point>]
   or: git branch [<options>] [-r] (-d | -D) <branch-name>...
   or: git branch [<options>] (-m | -M) [<old-branch>] <new-branch>
   or: git branch [<options>] [-r | -a] [--points-at]

Generic options
    -v, --verbose         show hash and subject, give twice for upstream branch
    -q, --quiet           suppress informational messages
    -t, --track           set up tracking mode (see git-pull(1))
    --set-upstream        change upstream info
    -u, --set-upstream-to <upstream>
                          change the upstream info
    --unset-upstream      Unset the upstream info
    --color[=<when>]      use colored output
    -r, --remotes         act on remote-tracking branches
    --contains <commit>   print only branches that contain the commit
    --abbrev[=<n>]        use <n> digits to display SHA-1s

Specific git-branch actions:
    -a, --all             list both remote-tracking and local branches
    -d, --delete          delete fully merged branch
    -D                    delete branch (even if not merged)
    -m, --move            move/rename a branch and its reflog
    -M                    move/rename a branch, even if target exists
    --list                list branch names
    -l, --create-reflog   create the branch's reflog
    --edit-description    edit the description for the branch
    -f, --force           force creation, move/rename, deletion
    --merged <commit>     print only branches that are merged
    --no-merged <commit>  print only branches that are not merged
    --column[=<style>]    list branches in columns
    --sort <key>          field name to sort on
    --points-at <object>  print only branches of the object

the result of running  git rev-parse HEAD:
4490b4e406fe7225a1bcdc55616d2a90bce83cd4

**Comment by innerlee** [comment]
do you need to warp flows? or simply extracting flows is enough?

for flow extraction, you may clone and build this repo. there are instructions in the README, and also https://github.com/open-mmlab/denseflow/blob/master/INSTALL.md

**Comment by Shuhan136** [comment]
> do you need to warp flows? or simply extracting flows is enough?
> 
> for flow extraction, you may clone and build this repo. there are instructions in the README, and also https://github.com/open-mmlab/denseflow/blob/master/INSTALL.md

Thanks very much！
